server:
  port: 0 #0번 포트는 랜덤 포트를 사용하겠다는 뜻

spring:
  application:
    name: user-service
  rabbitmq:
    host: localhost #연결할 host
    port: 5672 #직접 url로 들어갈 때는 15672이나 config server에서는 다음 포트번호로 접속한다
    user: guest
    password: guest
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
#  datasource:
#    driver-class-name: org.h2.Driver
#    url : jdbc:h2:mem:testdb
    #username: sa
    #password : 1234

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true #외부 검색 가능하도록
    service-url:
      defaltZone: http://192.168.0.20:8761/eureka #server의 위치 지정

greeting:
  message: Welcome to the Simple E-commerce


logging:
  level:
    com.zzarbttoo.userservice: DEBUG

        # refresh : microservice에 있는 configuration 정보를 가져오겠다는 뜻


#
##token 관련 작업
#token:
#  expiration_time: 86400000 #하루
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
#  secret: user_token #필요한 임의의 값